# Hyprland greetd sessions: Caelestia-AW and end4-pC.
{
  pkgs,
  lib,
  config,
  inputs,
  ...
}:

let
  polkitAgent = "${pkgs.kdePackages.polkit-kde-agent-1}/libexec/polkit-kde-authentication-agent-1";
  pactl = "${pkgs.pulseaudio}/bin/pactl";
  brightnessctl = "${pkgs.brightnessctl}/bin/brightnessctl";
  konsole = "${pkgs.kdePackages.konsole}/bin/konsole";

  # Shared Hyprland preamble. Super+Space stays free for Fcitx5/Mozc;
  # launchers use Super+R.
  sharedPreamble = ''
    monitor=,preferred,auto,1

    env = XDG_CURRENT_DESKTOP,Hyprland
    env = XDG_SESSION_DESKTOP,Hyprland
    env = XDG_SESSION_TYPE,wayland
    env = QT_QPA_PLATFORM,wayland
    env = MOZ_ENABLE_WAYLAND,1

    exec-once = dbus-update-activation-environment --systemd --all
    exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE QT_QPA_PLATFORM
    exec-once = ${polkitAgent}
    exec-once = fcitx5 -d --replace
    exec-once = wl-paste --type text --watch cliphist store
    exec-once = wl-paste --type image --watch cliphist store

    input {
      kb_layout = jp
      follow_mouse = 1
      touchpad {
        natural_scroll = false
        tap-to-click = true
      }
    }

    general {
      gaps_in = 4
      gaps_out = 8
      border_size = 2
    }

    decoration {
      rounding = 8
    }

    misc {
      disable_hyprland_logo = true
      force_default_wallpaper = 0
      vfr = true
    }

    # PulseAudio volume (PipeWire audio is off on sof-rt5682).
    bindel = , XF86AudioRaiseVolume, exec, ${pactl} set-sink-volume @DEFAULT_SINK@ +5%
    bindel = , XF86AudioLowerVolume, exec, ${pactl} set-sink-volume @DEFAULT_SINK@ -5%
    bindl = , XF86AudioMute, exec, ${pactl} set-sink-mute @DEFAULT_SINK@ toggle
    bindl = , XF86AudioMicMute, exec, ${pactl} set-source-mute @DEFAULT_SOURCE@ toggle
    bindel = , XF86MonBrightnessUp, exec, ${brightnessctl} set +5%
    bindel = , XF86MonBrightnessDown, exec, ${brightnessctl} set 5%-

    bind = SUPER, Return, exec, ${konsole}
    bind = SUPER, Q, killactive,
    bind = SUPER SHIFT, E, exit,
    bind = SUPER, F, fullscreen,
  '';

  caelestiaConf = ''
    ${sharedPreamble}
    exec-once = caelestia shell -d
    bind = SUPER, R, exec, caelestia shell drawers toggle launcher
  '';

  end4Conf = ''
    ${sharedPreamble}
    env = qsConfig,end4-pC
    env = QUICKSHELL_CONFIG_NAME,end4-pC
    exec-once = qs -c end4-pC
    bind = SUPER, Escape, global, quickshell:settingsToggle
    bind = SUPER, R, global, quickshell:searchToggle
  '';

  # Patch end4-pC so color/wallpaper scripts target this qs config name, not "ii".
  end4PcPatched =
    pkgs.runCommand "end4-pC-patched"
      {
        preferLocalBuild = true;
      }
      ''
        mkdir -p "$out"
        cp -a --no-preserve=mode ${inputs.end4-pc}/. "$out/"
        find "$out" -type f \( -name '*.sh' -o -name '*.qml' -o -name '*.py' \) \
          -exec sed -i \
            -e 's/QUICKSHELL_CONFIG_NAME="ii"/QUICKSHELL_CONFIG_NAME="end4-pC"/g' \
            -e 's/QUICKSHELL_CONFIG_NAME=ii/QUICKSHELL_CONFIG_NAME=end4-pC/g' \
            {} +
      '';
in
{
  imports = [
    inputs.caelestia-shell-aw.homeManagerModules.default
  ];

  # Start from Hyprland exec-once only (not every graphical-session / Plasma).
  programs.caelestia = {
    enable = true;
    systemd.enable = false;
    cli.enable = true;
    settings = {
      paths.wallpaperDir = "~/Pictures/Wallpapers";
    };
  };

  xdg.configFile."hypr/caelestia.conf".text = caelestiaConf;
  xdg.configFile."hypr/end4.conf".text = end4Conf;
  xdg.configFile."quickshell/end4-pC".source = end4PcPatched;

  # Drop Hyprland's first-run autogenerated lua (expects kitty).
  home.activation.removeAutogenHyprlandLua = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    rm -f "${config.home.homeDirectory}/.config/hypr/hyprland.lua"
  '';

  # Skip end4 FirstRunExperience wallpaper/matugen cascade on a fresh home.
  home.activation.end4SkipFirstRun = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    state="${config.home.homeDirectory}/.local/state/quickshell/user"
    mkdir -p "$state" \
      "${config.home.homeDirectory}/.config/illogical-impulse" \
      "${config.home.homeDirectory}/.local/state/quickshell/user/generated"
    if [ ! -f "$state/first_run.txt" ]; then
      printf '%s\n' 'This file is just here to confirm you have been greeted :>' \
        > "$state/first_run.txt"
    fi
  '';

  home.activation.caelestiaWallpaperDirs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "${config.home.homeDirectory}/Pictures/Wallpapers/Animated"
  '';

  home.packages = with pkgs; [
    # Caelestia-AW video wallpaper thumbnails / decode helpers
    ffmpeg
    python3Packages.pillow
  ];
}
