{
  config,
  pkgs,
  lib,
  ...
}:

let
  sessionData = config.services.displayManager.sessionData.desktops;

  mkWaylandSession =
    {
      id,
      name,
      comment,
      exec,
      desktopNames ? "Hyprland",
    }:
    let
      desktop = pkgs.writeText "${id}.desktop" ''
        [Desktop Entry]
        Name=${name}
        Comment=${comment}
        Exec=${exec}
        Type=Application
        DesktopNames=${desktopNames}
      '';
    in
    pkgs.runCommand "${id}-session"
      {
        passthru.providedSessions = [ id ];
      }
      ''
        mkdir -p "$out/share/wayland-sessions"
        cp ${desktop} "$out/share/wayland-sessions/${id}.desktop"
      '';

  # Console: no compositor — login shell on the VT. Use `gui <app>` for kiosk GUI.
  consoleSession = mkWaylandSession {
    id = "00-console";
    name = "Console";
    comment = "Text console without desktop environment (use: apps / gui <app>)";
    exec = "${pkgs.bashInteractive}/bin/bash -l";
    desktopNames = "Console";
  };

  hyprlandCaelestia = pkgs.writeShellApplication {
    name = "hyprland-caelestia";
    runtimeInputs = [
      pkgs.hyprland
      pkgs.systemd
    ];
    text = ''
      export XDG_CURRENT_DESKTOP=Hyprland
      export XDG_SESSION_DESKTOP=Hyprland
      export XDG_SESSION_TYPE=wayland
      export MITAC_SESSION=caelestia
      conf="''${XDG_CONFIG_HOME:-$HOME/.config}/hypr/caelestia.conf"
      if [ ! -f "$conf" ]; then
        printf 'missing Hyprland config: %s\n' "$conf" >&2
        exit 1
      fi
      # Avoid stock hyprland.lua taking over when --config is a classic .conf.
      export HYPRLAND_CONFIG="$conf"
      exec Hyprland --config "$conf"
    '';
  };

  hyprlandEnd4 = pkgs.writeShellApplication {
    name = "hyprland-end4";
    runtimeInputs = [
      pkgs.hyprland
      pkgs.quickshell
      pkgs.systemd
    ];
    text = ''
      export XDG_CURRENT_DESKTOP=Hyprland
      export XDG_SESSION_DESKTOP=Hyprland
      export XDG_SESSION_TYPE=wayland
      export MITAC_SESSION=end4
      export qsConfig=end4-pC
      export QT_QPA_PLATFORM=wayland
      conf="''${XDG_CONFIG_HOME:-$HOME/.config}/hypr/end4.conf"
      if [ ! -f "$conf" ]; then
        printf 'missing Hyprland config: %s\n' "$conf" >&2
        exit 1
      fi
      export HYPRLAND_CONFIG="$conf"
      exec Hyprland --config "$conf"
    '';
  };

  caelestiaSession = mkWaylandSession {
    id = "caelestia-aw";
    name = "Caelestia-AW";
    comment = "Hyprland with Caelestia shell (animated wallpapers)";
    exec = "${hyprlandCaelestia}/bin/hyprland-caelestia";
  };

  end4Session = mkWaylandSession {
    id = "end4-pc";
    name = "end4-pC";
    comment = "Hyprland with end4-pC Quickshell";
    exec = "${hyprlandEnd4}/bin/hyprland-end4";
  };

  # Only expose the sessions we support — hide stock hyprland / hyprland-uwsm
  # (autogenerated hyprland.lua expects kitty and confuses tuigreet).
  curatedSessions = pkgs.runCommand "mitac-greetd-sessions" { } ''
    mkdir -p "$out/wayland-sessions" "$out/xsessions"
    for f in \
      ${consoleSession}/share/wayland-sessions/*.desktop \
      ${caelestiaSession}/share/wayland-sessions/*.desktop \
      ${end4Session}/share/wayland-sessions/*.desktop
    do
      cp -f "$f" "$out/wayland-sessions/"
    done
    # Plasma / GNOME (and any other DE we keep)
    if [ -f ${sessionData}/share/wayland-sessions/plasma.desktop ]; then
      cp -f ${sessionData}/share/wayland-sessions/plasma.desktop "$out/wayland-sessions/"
    fi
    if [ -f ${sessionData}/share/wayland-sessions/gnome.desktop ]; then
      cp -f ${sessionData}/share/wayland-sessions/gnome.desktop "$out/wayland-sessions/"
    fi
    if [ -d ${sessionData}/share/xsessions ]; then
      cp -f ${sessionData}/share/xsessions/*.desktop "$out/xsessions/" 2>/dev/null || true
    fi
  '';

  # tuigreet default is `startx /usr/bin/env`, but NixOS only provides startx
  # when displayManager.startx.enable is on — and greeter PATH can still miss it.
  xsessionWrapper = pkgs.writeShellScript "tuigreet-xsession-wrapper" ''
    exec ${pkgs.xinit}/bin/startx ${pkgs.coreutils}/bin/env "$@"
  '';
in
{
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        user = "greeter";
        command = lib.concatStringsSep " " [
          "${lib.getExe pkgs.tuigreet}"
          "--time"
          "--asterisks"
          "--remember"
          "--remember-session"
          "--user-menu"
          "--sessions"
          "${curatedSessions}/wayland-sessions"
          "--xsessions"
          "${curatedSessions}/xsessions"
          "--xsession-wrapper"
          "${xsessionWrapper}"
        ];
      };
    };
  };

  # Suppress boot spam on the greeter TTY.
  systemd.services.greetd.serviceConfig = {
    Type = "idle";
    StandardInput = "tty";
    StandardOutput = "tty";
    StandardError = "journal";
    TTYReset = true;
    TTYVHangup = true;
    TTYVTDisallocate = true;
  };

  services.displayManager.sessionPackages = [
    consoleSession
    caelestiaSession
    end4Session
  ];

  # Wrappers on PATH for manual starts from an existing shell.
  environment.systemPackages = [
    hyprlandCaelestia
    hyprlandEnd4
  ];
}
