{
  config,
  pkgs,
  lib,
  ...
}:

let
  sessionData = config.services.displayManager.sessionData.desktops;

  mkWaylandSession =
    {
      id,
      name,
      comment,
      exec,
      desktopNames ? "Hyprland",
    }:
    let
      desktop = pkgs.writeText "${id}.desktop" ''
        [Desktop Entry]
        Name=${name}
        Comment=${comment}
        Exec=${exec}
        Type=Application
        DesktopNames=${desktopNames}
      '';
    in
    pkgs.runCommand "${id}-session"
      {
        passthru.providedSessions = [ id ];
      }
      ''
        mkdir -p "$out/share/wayland-sessions"
        cp ${desktop} "$out/share/wayland-sessions/${id}.desktop"
      '';

  # Console: authenticated TTY login shell (not a Wayland compositor).
  # Keep it under wayland-sessions so tuigreet can list it, but clear Wayland
  # env so `gui`/cage and apps see a real text session.
  consoleWrapper = pkgs.writeShellApplication {
    name = "mitac-console-session";
    runtimeInputs = [ pkgs.bashInteractive ];
    text = ''
      export XDG_SESSION_TYPE=tty
      export XDG_CURRENT_DESKTOP=Console
      export XDG_SESSION_DESKTOP=Console
      unset WAYLAND_DISPLAY DISPLAY
      exec ${pkgs.bashInteractive}/bin/bash -l
    '';
  };

  consoleSession = mkWaylandSession {
    id = "00-console";
    name = "Console";
    comment = "Text console without desktop environment (use: apps / gui <app>)";
    exec = "${consoleWrapper}/bin/mitac-console-session";
    desktopNames = "Console";
  };

  # Prefer start-hyprland (sets compositor env / portals) over raw Hyprland.
  hyprlandCaelestia = pkgs.writeShellApplication {
    name = "hyprland-caelestia";
    runtimeInputs = [
      pkgs.hyprland
      pkgs.systemd
      pkgs.dbus
    ];
    text = ''
      export XDG_CURRENT_DESKTOP=Hyprland
      export XDG_SESSION_DESKTOP=Hyprland
      export XDG_SESSION_TYPE=wayland
      export MITAC_SESSION=caelestia
      conf="''${XDG_CONFIG_HOME:-$HOME/.config}/hypr/caelestia.conf"
      if [ ! -f "$conf" ]; then
        printf 'missing Hyprland config: %s\n' "$conf" >&2
        exit 1
      fi
      # Avoid stock hyprland.lua taking over when --config is a classic .conf.
      export HYPRLAND_CONFIG="$conf"
      # Args after -- are forwarded to Hyprland by start-hyprland.
      if command -v start-hyprland >/dev/null 2>&1; then
        exec start-hyprland -- --config "$conf"
      fi
      exec Hyprland --config "$conf"
    '';
  };

  hyprlandEnd4 = pkgs.writeShellApplication {
    name = "hyprland-end4";
    runtimeInputs = [
      pkgs.hyprland
      pkgs.quickshell
      pkgs.systemd
      pkgs.dbus
    ];
    text = ''
      export XDG_CURRENT_DESKTOP=Hyprland
      export XDG_SESSION_DESKTOP=Hyprland
      export XDG_SESSION_TYPE=wayland
      export MITAC_SESSION=end4
      export qsConfig=end4-pC
      export QT_QPA_PLATFORM=wayland
      # end4 scripts that still look for the upstream ii name.
      export QUICKSHELL_CONFIG_NAME=end4-pC
      conf="''${XDG_CONFIG_HOME:-$HOME/.config}/hypr/end4.conf"
      if [ ! -f "$conf" ]; then
        printf 'missing Hyprland config: %s\n' "$conf" >&2
        exit 1
      fi
      export HYPRLAND_CONFIG="$conf"
      if command -v start-hyprland >/dev/null 2>&1; then
        exec start-hyprland -- --config "$conf"
      fi
      exec Hyprland --config "$conf"
    '';
  };

  caelestiaSession = mkWaylandSession {
    id = "caelestia-aw";
    name = "Caelestia-AW";
    comment = "Hyprland with Caelestia shell (animated wallpapers)";
    exec = "${hyprlandCaelestia}/bin/hyprland-caelestia";
  };

  end4Session = mkWaylandSession {
    id = "end4-pc";
    name = "end4-pC";
    comment = "Hyprland with end4-pC Quickshell";
    exec = "${hyprlandEnd4}/bin/hyprland-end4";
  };

  # Only expose the sessions we support — hide stock hyprland / hyprland-uwsm
  # (autogenerated hyprland.lua expects kitty and confuses tuigreet) and hide
  # Plasma X11 (unstable on this Chromebook Wayland stack).
  curatedSessions = pkgs.runCommand "mitac-greetd-sessions" { } ''
    mkdir -p "$out/wayland-sessions" "$out/xsessions"
    for f in \
      ${consoleSession}/share/wayland-sessions/*.desktop \
      ${caelestiaSession}/share/wayland-sessions/*.desktop \
      ${end4Session}/share/wayland-sessions/*.desktop
    do
      cp -f "$f" "$out/wayland-sessions/"
    done
    if [ -f ${sessionData}/share/wayland-sessions/plasma.desktop ]; then
      cp -f ${sessionData}/share/wayland-sessions/plasma.desktop "$out/wayland-sessions/"
    fi
    # Intentionally leave xsessions empty (no plasmax11).
  '';
in
{
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        user = "greeter";
        command = lib.concatStringsSep " " [
          "${lib.getExe pkgs.tuigreet}"
          "--time"
          "--asterisks"
          "--remember"
          "--remember-session"
          "--user-menu"
          "--sessions"
          "${curatedSessions}/wayland-sessions"
          "--xsessions"
          "${curatedSessions}/xsessions"
        ];
      };
    };
  };

  # Suppress boot spam on the greeter TTY.
  systemd.services.greetd.serviceConfig = {
    Type = "idle";
    StandardInput = "tty";
    StandardOutput = "tty";
    StandardError = "journal";
    TTYReset = true;
    TTYVHangup = true;
    TTYVTDisallocate = true;
  };

  # greetd already substasks login PAM (KWallet via Plasma); keep explicit.
  security.pam.services.greetd.kwallet.enable = true;

  services.displayManager.sessionPackages = [
    consoleSession
    caelestiaSession
    end4Session
  ];

  # Wrappers on PATH for manual starts from an existing shell.
  environment.systemPackages = [
    consoleWrapper
    hyprlandCaelestia
    hyprlandEnd4
  ];
}
